/* mfbmap.h */

#ifndef _MFBMAP_H
#define _MFBMAP_H

#define InverseAlu  vga16_InverseAlu
#define endtab  vga16_endtab
#define mask  vga16_mask
#define mergeRopBits  vga16_mergeRopBits
#define mfbAllocatePrivates  vga16_mfbAllocatePrivates
#define mfbBSFuncRec  vga16_mfbBSFuncRec
#define mfbBlackSolidFS  vga16_mfbBlackSolidFS
#define mfbBlackStippleFS  vga16_mfbBlackStippleFS
#define mfbBresD  vga16_mfbBresD
#define mfbBresS  vga16_mfbBresS
#define mfbChangeWindowAttributes  vga16_mfbChangeWindowAttributes
#define mfbCloseScreen  vga16_mfbCloseScreen
#define mfbCopyArea  vga16_mfbCopyArea
#define mfbCopyPixmap  vga16_mfbCopyPixmap
#define mfbCopyPlane  vga16_mfbCopyPlane
#define mfbCopyRotatePixmap  vga16_mfbCopyRotatePixmap
#define mfbCopyWindow  vga16_mfbCopyWindow
#define mfbCreateColormap  vga16_mfbCreateColormap
#define mfbCreateDefColormap  vga16_mfbCreateDefColormap
#define mfbCreateGC  vga16_mfbCreateGC
#define mfbCreatePixmap  vga16_mfbCreatePixmap
#define mfbCreateWindow  vga16_mfbCreateWindow
#define mfbDestroyColormap  vga16_mfbDestroyColormap
#define mfbDestroyPixmap  vga16_mfbDestroyPixmap
#define mfbDestroyWindow  vga16_mfbDestroyWindow
#define mfbDoBitblt  vga16_mfbDoBitblt
#define mfbDoBitbltCopy  vga16_mfbDoBitbltCopy
#define mfbDoBitbltCopyInverted  vga16_mfbDoBitbltCopyInverted
#define mfbDoBitbltGeneral  vga16_mfbDoBitbltGeneral
#define mfbDoBitbltOr  vga16_mfbDoBitbltOr
#define mfbDoBitbltXor  vga16_mfbDoBitbltXor
#define mfbFillPolyBlack  vga16_mfbFillPolyBlack
#define mfbFillPolyInvert  vga16_mfbFillPolyInvert
#define mfbFillPolyWhite  vga16_mfbFillPolyWhite
#define mfbGCPrivateIndex  vga16_mfbGCPrivateIndex
#define mfbGetImage  vga16_mfbGetImage
#define mfbGetSpans  vga16_mfbGetSpans
#define mfbHorzS  vga16_mfbHorzS
#define mfbImageGlyphBltBlack  vga16_mfbImageGlyphBltBlack
#define mfbImageGlyphBltWhite  vga16_mfbImageGlyphBltWhite
#define mfbInstallColormap  vga16_mfbInstallColormap
#define mfbInvertSolidFS  vga16_mfbInvertSolidFS
#define mfbInvertStippleFS  vga16_mfbInvertStippleFS
#define mfbLineSD  vga16_mfbLineSD
#define mfbLineSS  vga16_mfbLineSS
#define mfbListInstalledColormaps  vga16_mfbListInstalledColormaps
#define mfbMapWindow  vga16_mfbMapWindow
#define mfbPadPixmap  vga16_mfbPadPixmap
#define mfbPaintWindow  vga16_mfbPaintWindow
#define mfbPixmapToRegion  vga16_mfbPixmapToRegion
#define mfbPolyFillArcSolid  vga16_mfbPolyFillArcSolid
#define mfbPolyFillRect  vga16_mfbPolyFillRect
#define mfbPolyGlyphBltBlack  vga16_mfbPolyGlyphBltBlack
#define mfbPolyGlyphBltInvert  vga16_mfbPolyGlyphBltInvert
#define mfbPolyGlyphBltWhite  vga16_mfbPolyGlyphBltWhite
#define mfbPolyPoint  vga16_mfbPolyPoint
#define mfbPositionWindow  vga16_mfbPositionWindow
#define mfbPushPixels  vga16_mfbPushPixels
#define mfbPutImage  vga16_mfbPutImage
#define mfbQueryBestSize  vga16_mfbQueryBestSize
#define mfbRealizeFont  vga16_mfbRealizeFont
#define mfbReduceRop  vga16_mfbReduceRop
#define mfbRegisterCopyPlaneProc  vga16_mfbRegisterCopyPlaneProc
#define mfbResolveColor  vga16_mfbResolveColor
#define mfbRestoreAreas  vga16_mfbRestoreAreas
#define mfbSaveAreas  vga16_mfbSaveAreas
#define mfbScreenInit  vga16_mfbScreenInit
#define mfbSegmentSD  vga16_mfbSegmentSD
#define mfbSegmentSS  vga16_mfbSegmentSS
#define mfbSetScanline  vga16_mfbSetScanline
#define mfbSetSpans  vga16_mfbSetSpans
#define mfbSolidBlackArea  vga16_mfbSolidBlackArea
#define mfbSolidInvertArea  vga16_mfbSolidInvertArea
#define mfbSolidPP  vga16_mfbSolidPP
#define mfbSolidWhiteArea  vga16_mfbSolidWhiteArea
#define mfbStippleBlackArea  vga16_mfbStippleBlackArea
#define mfbStippleInvertArea  vga16_mfbStippleInvertArea
#define mfbStippleWhiteArea  vga16_mfbStippleWhiteArea
#define mfbTEGlyphBltBlack  vga16_mfbTEGlyphBltBlack
#define mfbTEGlyphBltWhite  vga16_mfbTEGlyphBltWhite
#define mfbTileAreaPPW  vga16_mfbTileAreaPPW
#define mfbTileAreaPPWCopy  vga16_mfbTileAreaPPWCopy
#define mfbTileAreaPPWGeneral  vga16_mfbTileAreaPPWGeneral
#define mfbTileFS  vga16_mfbTileFS
#define mfbUninstallColormap  vga16_mfbUninstallColormap
#define mfbUnmapWindow  vga16_mfbUnmapWindow
#define mfbUnnaturalStippleFS  vga16_mfbUnnaturalStippleFS
#define mfbUnnaturalTileFS  vga16_mfbUnnaturalTileFS
#define mfbUnrealizeFont  vga16_mfbUnrealizeFont
#define mfbValidateGC  vga16_mfbValidateGC
#define mfbVertS  vga16_mfbVertS
#define mfbWhiteSolidFS  vga16_mfbWhiteSolidFS
#define mfbWhiteStippleFS  vga16_mfbWhiteStippleFS
#define mfbWindowPrivateIndex  vga16_mfbWindowPrivateIndex
#define mfbXRotatePixmap  vga16_mfbXRotatePixmap
#define mfbYRotatePixmap  vga16_mfbYRotatePixmap
#define mfbZeroPolyArcSS  vga16_mfbZeroPolyArcSS
#define partmasks  vga16_partmasks
#define rmask  vga16_rmask
#define starttab  vga16_starttab

#endif
