/* $XFree86: xc/programs/Xserver/hw/xfree86/accel/p9000/p9000viper.h,v 3.1 1994/06/26 13:05:21 dawes Exp $ */
/*
 * Written by Erik Nygren
 *
 * This code may be freely incorporated in any program without royalty, as
 * long as the copyright notice stays intact.
 *
 * ERIK NYGREN DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
 * INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
 * EVENT SHALL ERIK NYGREN BE LIABLE FOR ANY SPECIAL, INDIRECT OR
 * CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
 * DATA OR PROFITS, WHETHER IN AN ACTION OF
 * CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
 * CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 *
 */

/* Bits for the Output Control Register */

#define VPR_VLB_OCR_BASE_A0000000     0x01
#define VPR_VLB_OCR_BASE_20000000     0x02
#define VPR_VLB_OCR_BASE_80000000     0x03
#define VPR_VLB_OCR_RESERVED_MASK     0x0C
#define VPR_VLB_OCR_ENABLE_P9000      0x10
#define VPR_VLB_OCR_ENABLE_W5186      0x80

extern p9000VendorRec p9000ViperVendor;
