.\" $XFree86: xc/programs/Xserver/hw/darwin/Xdarwin.man,v 1.4 2001/01/23 23:51:34 dawes Exp $
.\"
.TH XDARWIN 1 __vendorversion__
.SH NAME
Xdarwin \- X window system server for Darwin operating system
.SH SYNOPSIS
.B Xdarwin
[ options ] ...
.SH DESCRIPTION
#ifdef DARWIN_WITH_QUARTZ
.I Xdarwin
is the window server for Version 11 of the X window system on the Darwin
operating system.
.I Xdarwin
can be started from the Darwin text console, or while running the Mac OS X
Quartz window server.
.PP
When running from the console,
.I Xdarwin
acts as the window server and uses IOKit services to accesss the display framebuffer,
mouse and keyboard and to provide a layer of hardware abstraction. In console mode,
.I Xdarwin
will normally be started by the \fIxdm(1)\fP display manager or by a script
that runs the program \fIxinit(1)\fP.
.PP
When running with the Mac OS X Quartz window server,
.I Xdarwin
will normally be started with the Xmaster application. This application acts an
agent for
.I Xdarwin
to receive events and allows easy switching between the Mac OS X and X window
desktops. In this mode, CoreGraphics is used to capture and draw to the screen.
#else
.I Xdarwin
is the window server for Version 11 of the X window system on the Darwin
operating system. This version of
.I Xdarwin
can only be started from the Darwin text console. The Mac OS X Quartz window
server, if present, must be shut down. It uses IOKit services to accesss the display
framebuffer, mouse and keyboard and to provide a layer of hardware abstraction.
.I Xdarwin
will normally be started by the \fIxdm(1)\fP display manager or by a script
that runs the program \fIxinit(1)\fP.
#endif
.SH OPTIONS
.PP
In addition to the normal server options described in the \fIXserver(1)\fP
manual page, \fIXdarwin\fP accepts the following command line switches:
.TP 8
.B \-fakebuttons
Emulates a 3 button mouse using the Command and Option keys. Clicking the
first mouse button while holding down Command will act like clicking
button 2. Holding down Option will simulate button 3.
.TP 8
.B \-nofakebuttons
Do not emulate a 3 button mouse. This is the default.
#ifdef DARWIN_WITH_QUARTZ
.TP 8
.B "\-size \fIwidth\fP \fIheight\fP"
Sets the screeen resolution for the X server to use.
This option is ignored if \fB\-quartz\fP is specified.
.TP 8
.B "\-depth \fIdepth\fP"
Specifies the color bit depth to use. Currently only 8, 15, and 24 color bits
per pixel are supported.
This option is ignored if \fB\-quartz\fP is specified.
.TP 8
.B "\-refresh \fIrate\fP"
Gives the refresh rate to use in Hz. For LCD displays this should be 0.
This option is ignored if \fB\-quartz\fP is specified.
.TP 8
.B \-quartz
Run in parallel with the Mac OS X Quartz window server.
#else
.TP 8
.B "\-size \fIwidth\fP \fIheight\fP"
Sets the screeen resolution for the X server to use.
.TP 8
.B "\-depth \fIdepth\fP"
Specifies the color bit depth to use. Currently only 8, 15, and 24 color bits
per pixel are supported.
.TP 8
.B "\-refresh \fIrate\fP"
Gives the refresh rate to use in Hz. For LCD displays this should be 0.
#endif
.TP 8
.B \-showconfig
Print out the server version and patchlevel.
.TP 8
.B \-version
Same as \fB\-showconfig\fP.
.SH "SEE ALSO"
.PP
X(__miscmansuffix__), Xserver(1), xdm(1), xinit(1)
.SH BUGS
.I Xdarwin
and this man page still have many limitations. Some of the more obvious
ones are:
.br
- Only one display is supported.
.br
- The display mode can not be changed once the X server has started.
.br
- A screen saver is not supported.
.br
- The key repeat rate can not be changed.
.PP
.SH AUTHORS
Original Port to Mac OS X Server - John Carmack
.br
Port to Darwin 1.0 - Dave Zarzycki
.br
Improvements and bug fixes - Torrey T. Lyons

