/* $XFree86: xc/programs/Xserver/hw/xfree86/vga2/mfb/mfbmap.h,v 1.3tsi Exp $ */

/* mfbmap.h */

#ifndef _MFBMAP_H
#define _MFBMAP_H

#define InverseAlu  vga2_InverseAlu
#define endtab  vga2_endtab
#define mask  vga2_mask
#define mergeRopBits  vga2_mergeRopBits
#define mfbAllocatePrivates  vga2_mfbAllocatePrivates
#define mfbBSFuncRec  vga2_mfbBSFuncRec
#define mfbBlackSolidFS  vga2_mfbBlackSolidFS
#define mfbBlackStippleFS  vga2_mfbBlackStippleFS
#define mfbBresD  vga2_mfbBresD
#define mfbBresS  vga2_mfbBresS
#define mfbChangeWindowAttributes  vga2_mfbChangeWindowAttributes
#define mfbCloseScreen  vga2_mfbCloseScreen
#define mfbCopyArea  vga2_mfbCopyArea
#define mfbCopyPixmap  vga2_mfbCopyPixmap
#define mfbCopyPlane  vga2_mfbCopyPlane
#define mfbCopyRotatePixmap  vga2_mfbCopyRotatePixmap
#define mfbCopyWindow  vga2_mfbCopyWindow
#define mfbCreateColormap  vga2_mfbCreateColormap
#define mfbCreateDefColormap  vga2_mfbCreateDefColormap
#define mfbCreateGC  vga2_mfbCreateGC
#define mfbCreatePixmap  vga2_mfbCreatePixmap
#define mfbCreateWindow  vga2_mfbCreateWindow
#define mfbDestroyColormap  vga2_mfbDestroyColormap
#define mfbDestroyPixmap  vga2_mfbDestroyPixmap
#define mfbDestroyWindow  vga2_mfbDestroyWindow
#define mfbDoBitblt  vga2_mfbDoBitblt
#define mfbDoBitbltCopy  vga2_mfbDoBitbltCopy
#define mfbDoBitbltCopyInverted  vga2_mfbDoBitbltCopyInverted
#define mfbDoBitbltGeneral  vga2_mfbDoBitbltGeneral
#define mfbDoBitbltOr  vga2_mfbDoBitbltOr
#define mfbDoBitbltXor  vga2_mfbDoBitbltXor
#define mfbFillPolyBlack  vga2_mfbFillPolyBlack
#define mfbFillPolyInvert  vga2_mfbFillPolyInvert
#define mfbFillPolyWhite  vga2_mfbFillPolyWhite
#define mfbGCPrivateIndex  vga2_mfbGCPrivateIndex
#define mfbGetImage  vga2_mfbGetImage
#define mfbGetSpans  vga2_mfbGetSpans
#define mfbHorzS  vga2_mfbHorzS
#define mfbImageGlyphBltBlack  vga2_mfbImageGlyphBltBlack
#define mfbImageGlyphBltWhite  vga2_mfbImageGlyphBltWhite
#define mfbInstallColormap  vga2_mfbInstallColormap
#define mfbInvertSolidFS  vga2_mfbInvertSolidFS
#define mfbInvertStippleFS  vga2_mfbInvertStippleFS
#define mfbLineSD  vga2_mfbLineSD
#define mfbLineSS  vga2_mfbLineSS
#define mfbListInstalledColormaps  vga2_mfbListInstalledColormaps
#define mfbMapWindow  vga2_mfbMapWindow
#define mfbPadPixmap  vga2_mfbPadPixmap
#define mfbPaintWindow  vga2_mfbPaintWindow
#define mfbPixmapToRegion  vga2_mfbPixmapToRegion
#define mfbPolyFillArcSolid  vga2_mfbPolyFillArcSolid
#define mfbPolyFillRect  vga2_mfbPolyFillRect
#define mfbPolyGlyphBltBlack  vga2_mfbPolyGlyphBltBlack
#define mfbPolyGlyphBltInvert  vga2_mfbPolyGlyphBltInvert
#define mfbPolyGlyphBltWhite  vga2_mfbPolyGlyphBltWhite
#define mfbPolyPoint  vga2_mfbPolyPoint
#define mfbPositionWindow  vga2_mfbPositionWindow
#define mfbPushPixels  vga2_mfbPushPixels
#define mfbPutImage  vga2_mfbPutImage
#define mfbQueryBestSize  vga2_mfbQueryBestSize
#define mfbRealizeFont  vga2_mfbRealizeFont
#define mfbReduceRop  vga2_mfbReduceRop
#define mfbRegisterCopyPlaneProc  vga2_mfbRegisterCopyPlaneProc
#define mfbResolveColor  vga2_mfbResolveColor
#define mfbRestoreAreas  vga2_mfbRestoreAreas
#define mfbSaveAreas  vga2_mfbSaveAreas
#define mfbScreenInit  vga2_mfbScreenInit
#define mfbSegmentSD  vga2_mfbSegmentSD
#define mfbSegmentSS  vga2_mfbSegmentSS
#define mfbSetScanline  vga2_mfbSetScanline
#define mfbSetSpans  vga2_mfbSetSpans
#define mfbSolidBlackArea  vga2_mfbSolidBlackArea
#define mfbSolidInvertArea  vga2_mfbSolidInvertArea
#define mfbSolidPP  vga2_mfbSolidPP
#define mfbSolidWhiteArea  vga2_mfbSolidWhiteArea
#define mfbStippleBlackArea  vga2_mfbStippleBlackArea
#define mfbStippleInvertArea  vga2_mfbStippleInvertArea
#define mfbStippleWhiteArea  vga2_mfbStippleWhiteArea
#define mfbTEGlyphBltBlack  vga2_mfbTEGlyphBltBlack
#define mfbTEGlyphBltWhite  vga2_mfbTEGlyphBltWhite
#define mfbTileAreaPPW  vga2_mfbTileAreaPPW
#define mfbTileAreaPPWCopy  vga2_mfbTileAreaPPWCopy
#define mfbTileAreaPPWGeneral  vga2_mfbTileAreaPPWGeneral
#define mfbTileFS  vga2_mfbTileFS
#define mfbUninstallColormap  vga2_mfbUninstallColormap
#define mfbUnmapWindow  vga2_mfbUnmapWindow
#define mfbUnnaturalStippleFS  vga2_mfbUnnaturalStippleFS
#define mfbUnnaturalTileFS  vga2_mfbUnnaturalTileFS
#define mfbUnrealizeFont  vga2_mfbUnrealizeFont
#define mfbValidateGC  vga2_mfbValidateGC
#define mfbVertS  vga2_mfbVertS
#define mfbWhiteSolidFS  vga2_mfbWhiteSolidFS
#define mfbWhiteStippleFS  vga2_mfbWhiteStippleFS
#define mfbWindowPrivateIndex  vga2_mfbWindowPrivateIndex
#define mfbXRotatePixmap  vga2_mfbXRotatePixmap
#define mfbYRotatePixmap  vga2_mfbYRotatePixmap
#define mfbZeroPolyArcSS  vga2_mfbZeroPolyArcSS
#define partmasks  vga2_partmasks
#define rmask  vga2_rmask
#define starttab  vga2_starttab

#endif
