#!/bin/sh
mkdir tohtml
cd tohtml
if [ -f randr.tex ]; then
   echo 'randr.tex exists!'
fi
cp ../randr.* .
cp ../*.eps .
cp ../usenix.sty .
cat ../randr.tex | sed -e 's/^\\Xdecl/\\item'/ |
sed -e 's/^\\Xerror/\\item/' |
sed -e 's/^\\Xparam/\\item/' |
sed -e 's/^\\Xenum/\\item/' |
sed -e 's/^\\Xreply/\\item/' |
sed -e 's/\\croplength=/%/' |
sed -e 's/\\cropweight=/%/' |
sed -e 's/^\\Xstruct/\\item/' > randr.tex
latex2html -white -transparent -split 0 -nonavigation -mkdir -dir ../randr randr.tex
cd ..
rm -r tohtml
