#!gmake
#
# $Header: /vol1/history/xf86/xc/extras/ogl-sample/main/gfx/lib/opengl/drivers/DDX/Attic/GNUmakefile,v 1.1 2001/02/01 08:28:31 alanh Exp $

SUBDIR = drivers/DDX

CFILES =	     \
	ddxcx.c	     \
	ddxrgb.c     \
	ddxci.c	     \
	ddxscreens.c \
	$(NULL)

include $(GFXDIR)/defs/subdefs

headers headers_install apps:

libs libs_install install: default
