# This file is part of the FreeType project.
#
# It builds the library and test programs for emx-gcc and djgpp under MSDOS.
#
# You will need recent GNU make DOS port.
#
# Use this file while in the 'test' directory with the following statement:
#
#   make -f arch/msdos/Makefile.gcc

ARCH = arch/msdos
FT_MAKEFILE = $(ARCH)/Makefile.gcc

CC = gcc

LIBDIR = ../lib
INCDIRS = -I$(LIBDIR) -I$(LIBDIR)/$(ARCH) -I. -I$(LIBDIR)/extend

CFLAGS = -Wall -ansi -O2 -g $(INCDIRS)
# CFLAGS = -ansi -Wall -O2 -s $(INCDIRS)

# full-screen MSDOS driver
GDRIVER = $(ARCH)/gfs_dos.c

SRC = ftlint.c fttimer.c ftview.c ftzoom.c ftdump.c ftstring.c \
      common.c

GSRC = gmain.c display.c $(GDRIVER)
GOBJ = $(GSRC:.c=.o)


define create_response_file
  -del response
  $(foreach file,$^,$(shell echo $(file) >> response))
endef

%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<

%.exe:
	$(create_response_file)
	$(CC) $(CFLAGS) -o $@ @response


EXEFILES = ftview.exe ftlint.exe fttimer.exe ftdump.exe \
           ftstring.exe ftzoom.exe

.PHONY: all debug freetype freetype_debug \
        clean distclean do_clean depend


all: freetype $(EXEFILES)

debug: freetype_debug $(EXEFILES)

freetype:
	$(MAKE) -C $(LIBDIR) -f $(FT_MAKEFILE) all

freetype_debug:
	$(MAKE) -C $(LIBDIR) -f $(FT_MAKEFILE) debug

ftzoom.exe: $(GOBJ) ftzoom.o common.o $(LIBDIR)/libttf.a
ftview.exe: $(GOBJ) ftview.o common.o $(LIBDIR)/libttf.a
ftlint.exe: ftlint.o common.o $(LIBDIR)/libttf.a
ftdump.exe: ftdump.o common.o $(LIBDIR)/libttf.a
ftstring.exe: $(GOBJ) ftstring.o common.o $(LIBDIR)/libttf.a
fttimer.exe: $(GOBJ) fttimer.o common.o $(LIBDIR)/libttf.a


clean: do_clean
	$(MAKE) -C $(LIBDIR) -f $(FT_MAKEFILE) clean

distclean: do_clean
	$(MAKE) -C $(LIBDIR) -f $(FT_MAKEFILE) distclean
	-del dep.end
	-del *.exe
	-del core

do_clean:
	-del *.o
	-del response
	-del arch\msdos\gfs_dos.o

depend: $(SRC) $(GSRC)
	$(MAKE) -C $(LIBDIR) -f $(FT_MAKEFILE) depend
	$(create_response_file)
	$(CC) -E -M $(INCDIRS) @response > dep.end

ifeq (dep.end,$(wildcard dep.end))
  include dep.end
endif

# end of Makefile.gcc
