/* $XFree86$ */

#ifdef _PARSE_EDID_

#define EDID2_len 256

#define VERSION_SECTION 0
#define VERSION_LEN 1
#define VENDOR_SECTION (VERSION_SECTION + VERSION_LEN)
#define V_MANUFACURER 0
#define V_PROD_ID (V_MANUFACURER + 2)
#define V_WEEK (V_PROD_ID + 2)
#define V_YEAR (V_WEEK + 1)
#define VENDOR_LEN 7
#define MANUFACTURER_SECTION (VENDOR_SECTION + VENDOR_LEN)
#define MANUFACTURER_LEN 32
#define SERIAL_NO_SECTION (MANUFACTURER_SECTION + MANUFACTURER_LEN)
#define SERIAL_NO_LEN 16
#define UNUSED (SERIAL_NO_SECTION + SERIAL_NO_LEN)
#define UNUSED_LEN 8
#define DISPLAY_INTERFACE (UNUSED + UNUSED_LEN)
#define PHYS_INTERFACE 0
#define VIDEO_INTERFACE (PHYS_INTERFACE + 1)
#define INTERFACE_DATA_FORMAT (VIDEO_INTERFACE + 1)
#define INTERFACE_COLOR_ENCODING (INTERFACE_DATA_FORMAT + 8)
#define DISPLAY_INTERFACE_LEN 15
#define DISPLAY_DEVICE (DISPLAY_INTERFACE + DISPLAY_INTERFACE_LEN)
#define DISPLAY_TECHNOLOGY 0
#define DISPLAY_CHARACTER (DISPLAY_TECHNOLOGY + 1)
#define FEATURE_SUPPORT (DISPLAY_CHARACTER + 1) 
#define DISPLAY_DEVICE_LEN 5
#define DISPLAY_RESPONSE_TIME (DISPLAY_INTERFACE + DISPLAY_INTERFACE_LEN)
#define DISPLAY_RESPONSE_TIME_LEN 2
#define COLOR_DESCRIPTION (DISPLAY_RESPONSE_TIME + DISPLAY_RESONSE_TIME_LEN)
#define GAMMA 0
#define MAX_LUM (GAMMA + 4)
#define WHITE_POINT (MAX_LUM + 4)
#define COLOR_DESCRIPTION_LEN 28
#define DISPLAY_DIMENSION (COLOR_DESCRIPTION + COLOR_DESCRIPTION_LEN)
#define DISPLAY_SIZE 0
#define DISPLAY_ADDRESSABILITY (DISPLAY_SIZE + 4)
#define DISPLAY_PITCH (DISPLAY_ADDRESSABILITY + 4)
#define DISPLAY_DIMENION_LEN 10
#define UNUSED1 (DISPLAY_DIMENSION + DISPLAY_DIMENSION_LEN)
#define UNUSED1_LEN
#define GFT_SUPPORT (UNUSED1 + UNUSED1_LEN)
#define GFT_SUPPORT_LEN
#define TIMING_INFO_MAP (GFT_SUPPORT + GFT_SUPPORT_LEN)
#define TIMING_INFO_LEN 2
