#!/bin/sh
#
# Shell Skript to copy the object files, 
# needed for linking test_glint: 
# - lnx_video.o
# - xf86_PCI.o
# - miscutil.o
# - xf86_IlHack.o
#
# usage: cp_objfile xc-directory objfile
#
# $XFree86: $

if test $# -ne 2; then
    echo "usage: cp_objfile xc-directory objfile"; exit
fi

XC=$1
OBJECT=$2

TEST_GLINT_HOME=`pwd`

if !(test -f $XC/registry); then
  echo "Directory $XC doesn´t exist!"
  exit
fi

# compile and copy Object file

case "$OBJECT" in
    lnx_video.o)
	rm -f lnx_video.o
	cd $XC/programs/Xserver/hw/xfree86/os-support/linux
	rm -f lnx_video.o
	mv lnx_video.c lnx_video.c.orig
	sed -e 's/FatalError/printf/g' lnx_video.c.orig > lnx_video.c
	make CDEBUGFLAGS="-g -dDEBUG"
	mv lnx_video.o $TEST_GLINT_HOME
	mv lnx_video.c.orig lnx_video.c
	;;

    xf86_PCI.o)
	rm -f xf86_PCI.o
	cd $XC/programs/Xserver/hw/xfree86/common_hw
	rm -f xf86_PCI.o
	mv xf86_PCI.c xf86_PCI.c.orig 
	sed -e 's/ErrorF/printf/g' xf86_PCI.c.orig > xf86_PCI.c
	make CDEBUGFLAGS="-g -dDEBUG"
	mv xf86_PCI.o $TEST_GLINT_HOME
	mv xf86_PCI.c.orig xf86_PCI.c
	;;

    miscutil.o)
	rm -f miscutil.o
	cd $XC/lib/font/util
	rm -f miscutil.o
	make CDEBUGFLAGS="-g -dDEBUG"
	mv miscutil.o $TEST_GLINT_HOME
	;;

    xf86_IlHack.o)
	# compile and copy xf86_IlHack
	rm -f xf86_IlHack.o
	cd $XC/programs/Xserver/hw/xfree86/os-support/misc
	rm -f xf86_IlHack.o
	make CDEBUGFLAGS="-g -dDEBUG"
	mv xf86_IlHack.o $TEST_GLINT_HOME
	;;

    *)	
	echo "Object File \"$OBJECT\" doesn't exist!"
esac






